# Generated by Django 5.0.6 on 2024-06-20 07:42

from django.db import migrations, models #type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('bisu', '0002_samosavariety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='samosavariety',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]

    
